version: "3.3"
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  rcli:
    image: redis:latest
    container_name: redis_cli
    restart: always
    links:
      - redis
    command: redis-cli -h redis
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

volumes:
  redis_volume_data:
  redis_insight_volume_data:


networks:
  rabbitmq_net:
    driver: bridge
